@HostAddress = http://localhost:5168

GET {{HostAddress}}/openapi/v1.json

###

GET {{HostAddress}}/ping
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174000
Accept: application/json

###

GET {{HostAddress}}/tools
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174001
Accept: application/json

###

POST {{HostAddress}}/tools/getCurrentWeather/calls
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174002
Content-Type: application/json
Accept: application/json

{
    "name": "getCurrentWeather",
    "arguments": {
        "location": "New York"
    }
}

###

GET {{HostAddress}}/resources
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174003
Accept: application/json

###

GET {{HostAddress}}/resources/test%3A%2F%2Fstatic%2Fresource%2F1
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174033
Accept: application/json

###

GET {{HostAddress}}/prompts
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174013
Accept: application/json

###

GET {{HostAddress}}/prompts/code_review
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174004
Mcp-Arguments: { "code": "public class HelloWorld { public static void main(String[] args) { System.out.println(\"Hello, World!\"); } }" }
Mcp-Meta: { "foobar": "bazqux"}
Accept: application/json

###

POST {{HostAddress}}/resources/subscribe
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174004
Content-Type: application/json
Accept: application/json

{
    "uri": "test://static/resource/1"
}

###

GET {{HostAddress}}/notifications
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

POST {{HostAddress}}/notifications
Mcp-Protocol-Version: 2025-06-18
Mcp-Group-Id: c8ae327c-a2e5-4640-bcf1-f1add5db88e2
Content-Type: application/json

[]

###

POST {{HostAddress}}/resources/unsubscribe
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174005
Content-Type: application/json
Accept: application/json

{
    "uri": "test://static/resource/1"
}

###

POST {{HostAddress}}/tools/GuessTheNumber/calls
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174006
Content-Type: application/json
Accept: application/json

{
    "name": "GuessTheNumber"
}

###

GET {{HostAddress}}/tools/GuessTheNumber/calls/123e4567-e89b-12d3-a456-426614174006
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

GET {{HostAddress}}/requests
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

@McpRequestId = de866755-3ef3-432a-b346-04c1a2b1b73e

POST {{HostAddress}}/requests
Mcp-Protocol-Version: 2025-06-18
Content-Type: application/json
Accept: application/json
Mcp-Request-Id: {{McpRequestId}}

{
    "action": "accept",
    "content": {
        "Answer" : true
    }
}

###

POST {{HostAddress}}/requests
Mcp-Protocol-Version: 2025-06-18
Content-Type: application/json
Accept: application/json
Mcp-Request-Id: {{McpRequestId}}

{
    "action": "accept",
    "content": {
        "Name" : "Mike"
    }
}

###

POST {{HostAddress}}/requests
Mcp-Protocol-Version: 2025-06-18
Content-Type: application/json
Accept: application/json
Mcp-Request-Id: {{McpRequestId}}

{
    "action": "accept",
    "content": {
        "Guess" : 6
    }
}

###

POST {{HostAddress}}/tools/RunAWhile/calls
Mcp-Protocol-Version: 2025-06-18
Mcp-Request-Id: 123e4567-e89b-12d3-a456-426614174006
Content-Type: application/json
Accept: application/json

{
    "name": "RunAWhile",
    "arguments": {
        "seconds": 10
    }
}

###

GET {{HostAddress}}/tools/RunAWhile/calls/123e4567-e89b-12d3-a456-426614174006
Mcp-Protocol-Version: 2025-06-18
Accept: application/json
