@HostAddress = http://localhost:5168

GET {{HostAddress}}/openapi/v1.json

###

GET {{HostAddress}}/ping
Accept: application/json
Mcp-Protocol-Version: 2025-06-18

###

GET {{HostAddress}}/tools
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

POST {{HostAddress}}/tools/get_current_weather/calls
Mcp-Protocol-Version: 2025-06-18
Content-Type: application/json
Accept: application/json

{
    "name": "getCurrentWeather"
}

###

GET {{HostAddress}}/resources
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

POST {{HostAddress}}/resources/subscribe
Mcp-Protocol-Version: 2025-06-18
Content-Type: application/json
Accept: application/json

{
    "uri": "test://static/resource/1"
}

###

GET {{HostAddress}}/notifications
Mcp-Protocol-Version: 2025-06-18
Accept: application/json

###

POST {{HostAddress}}/notifications
Mcp-Protocol-Version: 2025-06-18
Mcp-Group-Id: c8ae327c-a2e5-4640-bcf1-f1add5db88e2
Content-Type: application/json

[]